package functionalj.types.list;

import java.util.function.Consumer;
import java.util.function.Function;
import java.util.function.Predicate;

import functionalj.functions.FuncUnit;
import lombok.val;

public interface FunctionalListPeekAddOn<DATA> {
    
    public FunctionalList<DATA> peek(FuncUnit<? super DATA> consumer);
    
    public default <T extends DATA> FunctionalList<DATA> peek(Class<T> clzz, Consumer<? super T> theConsumer) {
        return peek(value -> {
            if (!clzz.isInstance(value))
                return;
            
            val target = clzz.cast(value);
            theConsumer.accept(target);
        });
    }
    public default FunctionalList<DATA> peek(Predicate<? super DATA> selector, Consumer<? super DATA> theConsumer) {
        return peek(value -> {
            if (!selector.test(value))
                return;
            
            theConsumer.accept(value);
        });
    }
    public default <T> FunctionalList<DATA> peek(Function<? super DATA, T> mapper, Consumer<? super T> theConsumer) {
        return peek(value -> {
            val target = mapper.apply(value);
            theConsumer.accept(target);
        });
    }
    
    public default <T> FunctionalList<DATA> peek(Function<? super DATA, T> mapper, Predicate<? super T> selector, Consumer<? super T> theConsumer) {
        return peek(value -> {
            val target = mapper.apply(value);
            if (selector.test(target))
                theConsumer.accept(target);
        });
    }
    
}
// Generated by: functionalj.kinds.functor.DuplicateResultMapToOtherTypeMain
